name: Actions 😎

on: 
    push:
        branches: ["release"]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key:
            Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**',
            'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-
      # Build
      - uses: game-ci/unity-builder@v4
        env:
         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
         UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
         UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
         #unityVersion: '2022.3.56f1'
         targetPlatform: ${{ matrix.targetPlatform }}
         versioning: Semantic
      - uses: actions/upload-artifact@v3
        with:
            name: Build-${{ matrix.targetPlatform }}
            path: build/${{ matrix.targetPlatform }}
  publishWebGL:
    name: Publish for WebGL
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download WebGL Artifact
      uses: actions/download-artifact@v3
      with:
        name: Build-WebGL
        path: build/WebGL
    - name: Upload WebGL Version
      uses: manleydev/butler-publish-itchio-action@master
      env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
            CHANNEL: webgl
            ITCH_GAME: ${{ vars.ITCH_GAME }}
            ITCH_USER: ${{ secrets.ITCHIO_USER }}
            PACKAGE: build/WebGL
  publishWindows:
    name: Publish for Windows
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download StandaloneWindows64 Artifact
      uses: actions/download-artifact@v3
      with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64
    - name: Upload Windows Version
      uses: manleydev/butler-publish-itchio-action@master
      env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
            CHANNEL: windows
            ITCH_GAME: ${{ vars.ITCH_GAME }}
            ITCH_USER: ${{ secrets.ITCHIO_USER }}
            PACKAGE: build/StandaloneWindows64
  publishLinux:
    name: Publish for Linux
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download StandaloneLinux64 Artifact
      uses: actions/download-artifact@v3
      with:
        name: Build-StandaloneLinux64
        path: build/StandaloneLinux64
    - name: Upload Linux Version
      uses: manleydev/butler-publish-itchio-action@master
      env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
            CHANNEL: linux
            ITCH_GAME: ${{ vars.ITCH_GAME }}
            ITCH_USER: ${{ secrets.ITCHIO_USER }}
            PACKAGE: build/StandaloneLinux64
        
                            